name: tickettouch
description: Ticket sales for Events.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

module:
  androidX: true

dependencies:
  # flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # icons & fonts
  flutter_launcher_icons: ^0.12.0 #flutter pub run flutter_launcher_icons:main
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  font_awesome_flutter: ^10.2.1
  # utils
  shared_preferences: ^2.2.1  # Aktualisiert auf die neueste verfügbare Version
  rive_splash_screen: ^0.1.1
  rive: ^0.11.16  # Aktualisiert auf die neueste verfügbare Version
  hidden_drawer_menu: ^3.0.1
  smooth_page_indicator: ^1.1.0  # Aktualisiert auf die neueste verfügbare Version
  settings_ui: ^2.0.2  # Aktualisiert auf die neueste verfügbare Version
  theme_mode_handler: ^3.0.0
  google_nav_bar: ^5.0.6
  ticket_widget: ^0.0.1
  flutter_slidable: ^3.0.0
  slide_to_act_reborn: ^3.0.0
  image_picker: ^1.0.4
  # qr
  qr_code_scanner:
    git:
      url: https://github.com/X-SLAYER/qr_code_scanner.git
      ref: flutter-beta
  qr_flutter: ^4.1.0  # Aktualisiert auf die neueste verfügbare Version
  # flutterfire
  flutterfire_cli: ^0.2.7
  # firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  firebase_dynamic_links: ^5.3.4
  firebase_analytics: ^10.4.5
  firebase_remote_config: ^4.2.5
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  firebase_database: ^10.2.5
  # auth
  firebase_ui_auth: ^1.7.0
  firebase_ui_oauth: ^1.4.10
  firebase_ui_oauth_google: ^1.2.10
  firebase_ui_oauth_apple: ^1.2.10
  firebase_ui_oauth_facebook: ^1.2.10
  firebase_ui_oauth_twitter: ^1.2.10
  google_sign_in: ^6.1.5 # Aktualisiert auf die neueste verfügbare Version
  flutter_facebook_auth: ^6.0.1  # Aktualisiert auf die neueste verfügbare Version
  sign_in_with_apple: ^5.0.0  # Aktualisiert auf die neueste verfügbare Version
  email_validator: ^2.0.1
  crypto: ^3.0.3
  twitter_login: ^4.4.2  # Aktualisiert auf die neueste verfügbare Version
  # state management
  provider: ^6.0.5
  url_launcher: ^6.1.14
  loop_page_view: ^1.2.5
  another_transformer_page_view: ^2.0.1

# dev
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  chewie: ^1.7.0
  chewie_audio: ^1.5.0
  mockito: ^5.4.0

#override
dependency_overrides:
  http: ^1.1.0
  wakelock_plus: ^1.1.1

# app icons
flutter_icons:
  image_path: "assets/logos/1024.png"
  android: true
  min_sdk_android: 28
  ios: true
  remove_alpha_ios: true
  web:
    generate: true

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/animations/
    - assets/images/
    - assets/logos/

    # animations
    - assets/animations/splash_animation.riv

    # images
    - assets/images/account_avatar.png

    # logos
    - assets/logos/1024.png
    - assets/logos/google_logo.png

