// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDXiT8GtUes1kBiv0h1wyKPbtf6wFa3Hw',
    appId: '1:222241256146:web:8779cac94c41dcf802730b',
    messagingSenderId: '222241256146',
    projectId: 'eventassist-tickettouch',
    authDomain: 'eventassist-tickettouch.firebaseapp.com',
    databaseURL: 'https://eventassist-tickettouch-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'eventassist-tickettouch.appspot.com',
    measurementId: 'G-MCSVBZFX1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLM7T2QP_4U9-xFqsL61GVT9aurLQvRko',
    appId: '1:222241256146:android:f0899da62266c83402730b',
    messagingSenderId: '222241256146',
    projectId: 'eventassist-tickettouch',
    databaseURL: 'https://eventassist-tickettouch-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'eventassist-tickettouch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiMux76t19b5MYBQsSiT-KokIkGorHmqY',
    appId: '1:222241256146:ios:90bb3e6e345822cb02730b',
    messagingSenderId: '222241256146',
    projectId: 'eventassist-tickettouch',
    databaseURL: 'https://eventassist-tickettouch-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'eventassist-tickettouch.appspot.com',
    androidClientId: '222241256146-95oe45s8q9pvbfsn6hhgbfakkkrnhtl7.apps.googleusercontent.com',
    iosClientId: '222241256146-r4a0tss1ng681eadnt8n0ukghe77iei8.apps.googleusercontent.com',
    iosBundleId: 'eu.eventassist.tickettouch',
  );
}
